//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sip.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AdminSipEntities : DbContext
    {
        public AdminSipEntities()
            : base("name=AdminSipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int PKG_ADMINSIP2_AGREGARCONDICIONPRESTACION(Nullable<decimal> iDPRESS, string cONDICION, string fUNCION, string tIPO, string eSTADO, Nullable<System.DateTime> iNICIOVIGENCIA, string iSAPRE, ObjectParameter eXCEPT_TEXT)
        {
            var iDPRESSParameter = iDPRESS.HasValue ?
                new ObjectParameter("IDPRESS", iDPRESS) :
                new ObjectParameter("IDPRESS", typeof(decimal));
    
            var cONDICIONParameter = cONDICION != null ?
                new ObjectParameter("CONDICION", cONDICION) :
                new ObjectParameter("CONDICION", typeof(string));
    
            var fUNCIONParameter = fUNCION != null ?
                new ObjectParameter("FUNCION", fUNCION) :
                new ObjectParameter("FUNCION", typeof(string));
    
            var tIPOParameter = tIPO != null ?
                new ObjectParameter("TIPO", tIPO) :
                new ObjectParameter("TIPO", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var iNICIOVIGENCIAParameter = iNICIOVIGENCIA.HasValue ?
                new ObjectParameter("INICIOVIGENCIA", iNICIOVIGENCIA) :
                new ObjectParameter("INICIOVIGENCIA", typeof(System.DateTime));
    
            var iSAPREParameter = iSAPRE != null ?
                new ObjectParameter("ISAPRE", iSAPRE) :
                new ObjectParameter("ISAPRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_ADMINSIP2_AGREGARCONDICIONPRESTACION", iDPRESSParameter, cONDICIONParameter, fUNCIONParameter, tIPOParameter, eSTADOParameter, iNICIOVIGENCIAParameter, iSAPREParameter, eXCEPT_TEXT);
        }
    
        public virtual int PKG_ADMINSIP2_AGREGARMEDICO(Nullable<decimal> rUT, string nOMBRE, Nullable<decimal> iDPREST, Nullable<decimal> iDPRESS, string iSAPRE, ObjectParameter eXCEPT_TEXT)
        {
            var rUTParameter = rUT.HasValue ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(decimal));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var iDPRESTParameter = iDPREST.HasValue ?
                new ObjectParameter("IDPREST", iDPREST) :
                new ObjectParameter("IDPREST", typeof(decimal));
    
            var iDPRESSParameter = iDPRESS.HasValue ?
                new ObjectParameter("IDPRESS", iDPRESS) :
                new ObjectParameter("IDPRESS", typeof(decimal));
    
            var iSAPREParameter = iSAPRE != null ?
                new ObjectParameter("ISAPRE", iSAPRE) :
                new ObjectParameter("ISAPRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_ADMINSIP2_AGREGARMEDICO", rUTParameter, nOMBREParameter, iDPRESTParameter, iDPRESSParameter, iSAPREParameter, eXCEPT_TEXT);
        }
    
        public virtual int PKG_ADMINSIP2_AGREGARPRESTACION(string iSAPRE, Nullable<decimal> cODPAQUETE, string dESCRIPCION, ObjectParameter eXCEPT_TEXT)
        {
            var iSAPREParameter = iSAPRE != null ?
                new ObjectParameter("ISAPRE", iSAPRE) :
                new ObjectParameter("ISAPRE", typeof(string));
    
            var cODPAQUETEParameter = cODPAQUETE.HasValue ?
                new ObjectParameter("CODPAQUETE", cODPAQUETE) :
                new ObjectParameter("CODPAQUETE", typeof(decimal));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_ADMINSIP2_AGREGARPRESTACION", iSAPREParameter, cODPAQUETEParameter, dESCRIPCIONParameter, eXCEPT_TEXT);
        }
    
        public virtual int PKG_ADMINSIP2_AGREGARPRESTADOR(string iSAPRE, Nullable<decimal> rUT, string nOMBRE, Nullable<decimal> rUTINSTITUCION, Nullable<decimal> sECUENCIA, string eSTADO, Nullable<System.DateTime> iNICIOVIGENCIA, string oBSERVACION, string dIRECCION, string tELEFONO, string sITIOWEB, ObjectParameter eXCEPT_TEXT)
        {
            var iSAPREParameter = iSAPRE != null ?
                new ObjectParameter("ISAPRE", iSAPRE) :
                new ObjectParameter("ISAPRE", typeof(string));
    
            var rUTParameter = rUT.HasValue ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(decimal));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var rUTINSTITUCIONParameter = rUTINSTITUCION.HasValue ?
                new ObjectParameter("RUTINSTITUCION", rUTINSTITUCION) :
                new ObjectParameter("RUTINSTITUCION", typeof(decimal));
    
            var sECUENCIAParameter = sECUENCIA.HasValue ?
                new ObjectParameter("SECUENCIA", sECUENCIA) :
                new ObjectParameter("SECUENCIA", typeof(decimal));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var iNICIOVIGENCIAParameter = iNICIOVIGENCIA.HasValue ?
                new ObjectParameter("INICIOVIGENCIA", iNICIOVIGENCIA) :
                new ObjectParameter("INICIOVIGENCIA", typeof(System.DateTime));
    
            var oBSERVACIONParameter = oBSERVACION != null ?
                new ObjectParameter("OBSERVACION", oBSERVACION) :
                new ObjectParameter("OBSERVACION", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var tELEFONOParameter = tELEFONO != null ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(string));
    
            var sITIOWEBParameter = sITIOWEB != null ?
                new ObjectParameter("SITIOWEB", sITIOWEB) :
                new ObjectParameter("SITIOWEB", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_ADMINSIP2_AGREGARPRESTADOR", iSAPREParameter, rUTParameter, nOMBREParameter, rUTINSTITUCIONParameter, sECUENCIAParameter, eSTADOParameter, iNICIOVIGENCIAParameter, oBSERVACIONParameter, dIRECCIONParameter, tELEFONOParameter, sITIOWEBParameter, eXCEPT_TEXT);
        }
    
        public virtual int PKG_ADMINSIP2_AGREGARRESTRICCIONEXCEL(Nullable<decimal> iDPRESTACION, string cODPLAN, string iSAPRE, ObjectParameter eXCEPT_TEXT)
        {
            var iDPRESTACIONParameter = iDPRESTACION.HasValue ?
                new ObjectParameter("IDPRESTACION", iDPRESTACION) :
                new ObjectParameter("IDPRESTACION", typeof(decimal));
    
            var cODPLANParameter = cODPLAN != null ?
                new ObjectParameter("CODPLAN", cODPLAN) :
                new ObjectParameter("CODPLAN", typeof(string));
    
            var iSAPREParameter = iSAPRE != null ?
                new ObjectParameter("ISAPRE", iSAPRE) :
                new ObjectParameter("ISAPRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_ADMINSIP2_AGREGARRESTRICCIONEXCEL", iDPRESTACIONParameter, cODPLANParameter, iSAPREParameter, eXCEPT_TEXT);
        }
    
        public virtual int PKG_ADMINSIP2_EDITARPRESTACION(Nullable<decimal> cODPAQUETEANTERIOR, string iSAPRE, Nullable<decimal> cODPAQUETENUEVO, string dESCRIPCION, ObjectParameter eXCEPT_TEXT)
        {
            var cODPAQUETEANTERIORParameter = cODPAQUETEANTERIOR.HasValue ?
                new ObjectParameter("CODPAQUETEANTERIOR", cODPAQUETEANTERIOR) :
                new ObjectParameter("CODPAQUETEANTERIOR", typeof(decimal));
    
            var iSAPREParameter = iSAPRE != null ?
                new ObjectParameter("ISAPRE", iSAPRE) :
                new ObjectParameter("ISAPRE", typeof(string));
    
            var cODPAQUETENUEVOParameter = cODPAQUETENUEVO.HasValue ?
                new ObjectParameter("CODPAQUETENUEVO", cODPAQUETENUEVO) :
                new ObjectParameter("CODPAQUETENUEVO", typeof(decimal));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_ADMINSIP2_EDITARPRESTACION", cODPAQUETEANTERIORParameter, iSAPREParameter, cODPAQUETENUEVOParameter, dESCRIPCIONParameter, eXCEPT_TEXT);
        }
    
        public virtual int PKG_ADMINSIP2_ELIMINARMEDICO(Nullable<decimal> rUT, ObjectParameter eXCEPT_TEXT)
        {
            var rUTParameter = rUT.HasValue ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_ADMINSIP2_ELIMINARMEDICO", rUTParameter, eXCEPT_TEXT);
        }
    
        public virtual int PKG_ADMINSIP2_ELIMINARPRESTADOR(Nullable<decimal> rUT, string iSAPRE, ObjectParameter eXCEPT_TEXT)
        {
            var rUTParameter = rUT.HasValue ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(decimal));
    
            var iSAPREParameter = iSAPRE != null ?
                new ObjectParameter("ISAPRE", iSAPRE) :
                new ObjectParameter("ISAPRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_ADMINSIP2_ELIMINARPRESTADOR", rUTParameter, iSAPREParameter, eXCEPT_TEXT);
        }
    
        public virtual int PKG_ADMINSIP2_ELIMINARRESTRICCION(string cODPLAN, string iSAPRE, ObjectParameter eXCEPT_TEXT)
        {
            var cODPLANParameter = cODPLAN != null ?
                new ObjectParameter("CODPLAN", cODPLAN) :
                new ObjectParameter("CODPLAN", typeof(string));
    
            var iSAPREParameter = iSAPRE != null ?
                new ObjectParameter("ISAPRE", iSAPRE) :
                new ObjectParameter("ISAPRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_ADMINSIP2_ELIMINARRESTRICCION", cODPLANParameter, iSAPREParameter, eXCEPT_TEXT);
        }
    
        public virtual ObjectResult<ListarPrestacionesEntity> PKG_ADMINSIP2_LISTARPRESTACIONES(ObjectParameter eXCEPT_TEXT)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarPrestacionesEntity>("PKG_ADMINSIP2_LISTARPRESTACIONES", eXCEPT_TEXT);
        }
    
        public virtual ObjectResult<ObtenerMedicoEntity> PKG_ADMINSIP2_OBTENERMEDICOS(Nullable<decimal> pRESTACION_ID, Nullable<decimal> pRESTADOR_ID, string iSAPRE, ObjectParameter eXCEPT_TEXT)
        {
            var pRESTACION_IDParameter = pRESTACION_ID.HasValue ?
                new ObjectParameter("PRESTACION_ID", pRESTACION_ID) :
                new ObjectParameter("PRESTACION_ID", typeof(decimal));
    
            var pRESTADOR_IDParameter = pRESTADOR_ID.HasValue ?
                new ObjectParameter("PRESTADOR_ID", pRESTADOR_ID) :
                new ObjectParameter("PRESTADOR_ID", typeof(decimal));
    
            var iSAPREParameter = iSAPRE != null ?
                new ObjectParameter("ISAPRE", iSAPRE) :
                new ObjectParameter("ISAPRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerMedicoEntity>("PKG_ADMINSIP2_OBTENERMEDICOS", pRESTACION_IDParameter, pRESTADOR_IDParameter, iSAPREParameter, eXCEPT_TEXT);
        }
    
        public virtual ObjectResult<ObtenerPrestacionesEntity> PKG_ADMINSIP2_OBTENERPRESTACIONES(string iSAPRE, ObjectParameter eXCEPT_TEXT)
        {
            var iSAPREParameter = iSAPRE != null ?
                new ObjectParameter("ISAPRE", iSAPRE) :
                new ObjectParameter("ISAPRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerPrestacionesEntity>("PKG_ADMINSIP2_OBTENERPRESTACIONES", iSAPREParameter, eXCEPT_TEXT);
        }
    
        public virtual ObjectResult<ObtenerPrestadoresEntity> PKG_ADMINSIP2_OBTENERPRESTADORES(string iSAPRE, ObjectParameter eXCEPT_TEXT)
        {
            var iSAPREParameter = iSAPRE != null ?
                new ObjectParameter("ISAPRE", iSAPRE) :
                new ObjectParameter("ISAPRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerPrestadoresEntity>("PKG_ADMINSIP2_OBTENERPRESTADORES", iSAPREParameter, eXCEPT_TEXT);
        }
    
        public virtual ObjectResult<ObtenerRestriccionesEntity> PKG_ADMINSIP2_OBTENERRESTRICCIONES(string cODPLAN, string iSAPRE, ObjectParameter eXCEPT_TEXT)
        {
            var cODPLANParameter = cODPLAN != null ?
                new ObjectParameter("CODPLAN", cODPLAN) :
                new ObjectParameter("CODPLAN", typeof(string));
    
            var iSAPREParameter = iSAPRE != null ?
                new ObjectParameter("ISAPRE", iSAPRE) :
                new ObjectParameter("ISAPRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerRestriccionesEntity>("PKG_ADMINSIP2_OBTENERRESTRICCIONES", cODPLANParameter, iSAPREParameter, eXCEPT_TEXT);
        }
    
        public virtual ObjectResult<ObtenerSolicitudesEntity> PKG_ADMINSIP2_OBTENERSOLICITUDES(string aCCION, Nullable<decimal> vAR_AUX, ObjectParameter eXCEPT_TEXT)
        {
            var aCCIONParameter = aCCION != null ?
                new ObjectParameter("ACCION", aCCION) :
                new ObjectParameter("ACCION", typeof(string));
    
            var vAR_AUXParameter = vAR_AUX.HasValue ?
                new ObjectParameter("VAR_AUX", vAR_AUX) :
                new ObjectParameter("VAR_AUX", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerSolicitudesEntity>("PKG_ADMINSIP2_OBTENERSOLICITUDES", aCCIONParameter, vAR_AUXParameter, eXCEPT_TEXT);
        }
    
        public virtual int PKG_ADMINSIP2_TERMINARVIGENCIAPRESTACION(Nullable<decimal> cODPAQUETE, ObjectParameter eXCEPT_TEXT)
        {
            var cODPAQUETEParameter = cODPAQUETE.HasValue ?
                new ObjectParameter("CODPAQUETE", cODPAQUETE) :
                new ObjectParameter("CODPAQUETE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_ADMINSIP2_TERMINARVIGENCIAPRESTACION", cODPAQUETEParameter, eXCEPT_TEXT);
        }
    }
}
