//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sip.Models.Entities
{
    using System;
    
    public partial class Beneficiario
    {
        public Nullable<decimal> RUT { get; set; }
        public Nullable<decimal> SECUENCIA { get; set; }
        public string APEPAT { get; set; }
        public string APEMAT { get; set; }
        public string NOMBRE { get; set; }
        public string DV { get; set; }
        public string INICIOVIGENCIA { get; set; }
        public string EMAIL { get; set; }
        public string FONO1 { get; set; }
        public string CELULAR { get; set; }
    }
}
