//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sip.Models.Entities
{
    using System;
    
    public partial class Condicion
    {
        public string PRESCOND_TCONCIDICION { get; set; }
        public string PRESCOND_XTIPO { get; set; }
        public string PRESCOND_XESTADO { get; set; }
        public string PRESCOND_FINICIO_VIGENCIA { get; set; }
        public string PRESCOND_FTERMINO_VIGENCIA { get; set; }
        public string ISAP_CEMPRESA { get; set; }
    }
}
