//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sip.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAIL_PRESTADOR_SIP
    {
        public short PRESTSIP_ID { get; set; }
        public string MAPRES_TCORREO { get; set; }
        public string ISAP_CEMPRESA { get; set; }
        public string MAPRES_XESTADO { get; set; }
        public Nullable<System.DateTime> MAPRES_FINICIO_VIGENCIA { get; set; }
        public Nullable<System.DateTime> MAPRES_FTERMINO_VIGENCIA { get; set; }
    }
}
