//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sip.Models.Entities
{
    using System;
    
    public partial class ObtenerPrestacionesEntity
    {
        public decimal CODPAQUETE { get; set; }
        public string DESCRIPCION { get; set; }
        public string ISAPRE { get; set; }
        public string ESTADO { get; set; }
        public System.DateTime INICIOVIGENCIA { get; set; }
        public Nullable<System.DateTime> TERMINOVIGENCIA { get; set; }
    }
}
