//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sip.Models.Entities
{
    using System;
    
    public partial class ObtenerSolicitudesEntity
    {
        public decimal IDSOLICITUD { get; set; }
        public string PRESTACION { get; set; }
        public string PRESTADOR { get; set; }
        public string ISAPRE { get; set; }
        public string NOMBREAFILIADO { get; set; }
        public string ESTADO { get; set; }
    }
}
