//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sip.Models.Entities
{
    using System;
    
    public partial class Prestador
    {
        public decimal PRESTSIP_ID { get; set; }
        public decimal PRTA_NRUT { get; set; }
        public string PRTA_NOMBRE { get; set; }
        public decimal PRTA_NRUT_INSTITUCION { get; set; }
        public decimal PRTA_NSECUEN_INSTITUCION { get; set; }
        public string ISAP_CEMPRESA { get; set; }
        public string PRESTSIP_XESTADO { get; set; }
        public string PRESTSIP_FINICIO_VIGENCIA { get; set; }
        public string PRESTSIP_FTERMINO_VIGENCIA { get; set; }
        public string PRESTSIP_OBSERVACION { get; set; }
        public string TRAMO { get; set; }
        public Nullable<decimal> COPAGO { get; set; }
        public string PRESTSIP_DIRECCION { get; set; }
        public string PRESTSIP_TELEFONO { get; set; }
        public string PRESTSIP_DIRWEB { get; set; }
    }
}
