//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sip.Models.Entities
{
    using System;
    
    public partial class Prestacion
    {
        public decimal PRESSIP_ID { get; set; }
        public decimal PRES_CCOD_PAQUETE { get; set; }
        public string PAQU_DESCRIPCION { get; set; }
        public string PRESSIP_XESTADO { get; set; }
        public string PRESSIP_FINICIO_VIGENCIA { get; set; }
        public string PRESSIP_FTERMINO_VIGENCIA { get; set; }
        public string ISAP_CEMPRESA { get; set; }
    }
}
