//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sip.Models.Entities
{
    using System;
    
    public partial class PresupuestoSip
    {
        public decimal SOLSIP_ID { get; set; }
        public decimal AFIL_NRUT { get; set; }
        public string AFIL_TNOMBRES { get; set; }
        public string AFIL_TAPELLIDO_PATERNO { get; set; }
        public string AFIL_TAPELLIDO_MATERNO { get; set; }
        public string INICIOVIGENCIA { get; set; }
        public string ISAP_CEMPRESA { get; set; }
        public decimal CARG_NRUT { get; set; }
        public string SOLISIP_FSOLICITUD { get; set; }
        public decimal PRESSIP_ID { get; set; }
        public string PAQU_DESCRIPCION { get; set; }
        public decimal PRES_CCOD_PAQUETE { get; set; }
        public Nullable<decimal> PRESTSIP_ID { get; set; }
        public string TRAMO { get; set; }
        public decimal CATSIP_NCATEGORIA { get; set; }
        public string CANAL { get; set; }
        public decimal SOLISIP_EJEC_NRUT { get; set; }
        public string SOLISIP_AGENCIA { get; set; }
        public string SOLISIP_XESTADO { get; set; }
        public string SOLISIP_FESTADO { get; set; }
        public string PLSA_CCOD { get; set; }
    }
}
