//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sip.Models.Entities
{
    using System;
    
    public partial class Staff
    {
        public decimal PRTA_NRUT { get; set; }
        public string STPREST_NOMBRE_PRES { get; set; }
        public string STPREST_XESTADO { get; set; }
        public string STPREST_FINICIO_VIGENCIA { get; set; }
        public string STPREST_FTERMINO_VIGENCIA { get; set; }
        public string ISAP_CEMPRESA { get; set; }
    }
}
