//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sip.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AFILIADOSIP
    {
        public int AFIL_NRUT { get; set; }
        public string AFIL_XDV { get; set; }
        public string AFIL_TNOMBRES { get; set; }
        public string AFIL_TAPELLIDO_PATERNO { get; set; }
        public string AFIL_TAPELLIDO_MATERNO { get; set; }
        public string ISAP_CEMPRESA { get; set; }
        public string PLSA_CCOD { get; set; }
        public string TRAMO { get; set; }
        public string TIENECOBERTURASIP { get; set; }
        public string TIENERESTRICCIONES { get; set; }
    }
}
