//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sip.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sip.Resources.Messages.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener información del afiliado cuyo  Run  es {1}, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_Afiliado {
            get {
                return ResourceManager.GetString("Ex_Afiliado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener información de los beneficiarios autorizados a utilizar la prestación {0} para el afiliado  {1}, revise el archivo de log para obtener más información.
        /// </summary>
        internal static string Ex_Beneficiario {
            get {
                return ResourceManager.GetString("Ex_Beneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener información sobre las condiciones de acceso a la prestación {0} para la isapre {1}, revise el archivo de log para obtener más información.
        /// </summary>
        internal static string Ex_Condiciones {
            get {
                return ResourceManager.GetString("Ex_Condiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo generar el presupuesto Sip, revise el log para obtener más información..
        /// </summary>
        internal static string Ex_CreaSip {
            get {
                return ResourceManager.GetString("Ex_CreaSip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo enviar el correo elect´rnico al prestador..
        /// </summary>
        internal static string Ex_Mail {
            get {
                return ResourceManager.GetString("Ex_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener información de los prestadores asociados al plan de salud {0}  y la prestación {1}, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_Prestador {
            get {
                return ResourceManager.GetString("Ex_Prestador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener información de las prestaciones para el plan de salud {0} e isapre {1}, revise el archivo de log para obtener más información.
        /// </summary>
        internal static string Ex_Prestcacion {
            get {
                return ResourceManager.GetString("Ex_Prestcacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener la información del presupuesto asociado al identificador {0}, revise el archivo de log para obtener más información.
        /// </summary>
        internal static string Ex_Presupuesto {
            get {
                return ResourceManager.GetString("Ex_Presupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan del afiliado {0} no tiene cobertura para obtener el beneficio..
        /// </summary>
        internal static string Ex_SinCobertura {
            get {
                return ResourceManager.GetString("Ex_SinCobertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener información del staff médico asociados a prestador  {0}  y la prestación {1}, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string EX_Staff {
            get {
                return ResourceManager.GetString("EX_Staff", resourceCulture);
            }
        }
    }
}
